# Generated by Django 6.0.7 on 2026-07-27 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_sv', models.TextField(verbose_name='fråga')),
                ('type', models.CharField(choices=[('boolean', 'Ja/Nej'), ('multiple_choice', 'Flerval'), ('number', 'Nummer')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='Svarsalternativ, endast för flerval. Lista av strängar.')),
                ('status', models.CharField(choices=[('draft', 'Utkast'), ('live', 'Live'), ('archived', 'Arkiverad')], default='draft', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('host', 'Värd'), ('guest_suggested', 'Gästförslag')], default='host', max_length=20)),
                ('suggestion_review_status', models.CharField(blank=True, choices=[('pending', 'Väntar'), ('promoted', 'Godkänd'), ('archived', 'Avvisad')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age_bucket', models.CharField(choices=[('20s', '20-talet'), ('30s', '30-talet'), ('40s', '40-talet'), ('50+', '50 eller äldre')], max_length=8)),
                ('sex', models.CharField(choices=[('male', 'Man'), ('female', 'Kvinna')], max_length=8)),
                ('side', models.CharField(choices=[('bride', 'Brudens sida'), ('groom', 'Brudgummens sida'), ('both', 'Bådas sida')], max_length=8)),
                ('relation', models.CharField(choices=[('friend', 'Vän'), ('family', 'Familj'), ('plus_one', 'Plus one')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BigScreenState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('statistics', 'Statistik'), ('guessing_game', 'Gissningslek')], default='statistics', max_length=20)),
                ('breakdown', models.CharField(choices=[('overall', 'Alla'), ('sex', 'Kön'), ('age', 'Åldersgrupp'), ('side', 'Sida'), ('relation', 'Relation')], default='overall', max_length=10)),
                ('aggregation', models.CharField(blank=True, choices=[('avg', 'Medel'), ('median', 'Median'), ('min', 'Min'), ('max', 'Max'), ('count_above_threshold', 'Antal över tröskel')], max_length=25, null=True)),
                ('aggregation_threshold', models.FloatField(blank=True, help_text="Tröskelvärde för 'Antal över tröskel'.", null=True)),
                ('revealed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pulse.question')),
            ],
            options={
                'verbose_name': 'Big screen state',
                'verbose_name_plural': 'Big screen state',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='suggested_by_respondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_questions', to='pulse.respondent'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.JSONField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='pulse.question')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='pulse.respondent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('respondent', 'question'), name='one_response_per_question')],
            },
        ),
    ]
