# Generated by Django 6.0.7 on 2026-08-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0002_replace_age_bucket_with_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='relation',
            field=models.CharField(choices=[('friend', 'Vän'), ('family', 'Familj'), ('plus_one', 'Plus en')], max_length=8),
        ),
    ]
