# Generated by Django 6.0.7 on 2026-09-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0004_question_is_system_and_age_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigscreenstate',
            name='style',
            field=models.CharField(choices=[('generic', 'Standard'), ('podium', 'Podium'), ('bouquet', 'Bukett')], default='generic', max_length=10),
        ),
    ]
