# Generated by Django 6.0.7 on 2026-09-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0005_bigscreenstate_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_poster_text', models.TextField(default='Svara på några snabba, lite kluriga frågor om dig själv — helt anonymt, tar en minut. Svaren blir till en bild av oss alla här, som dyker upp på storbild under kvällen.', help_text='Brödtexten på QR-skylten (/qr/), under rubriken.')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
