# Generated by Django 6.0.7 on 2026-09-18 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0005_bigscreenstate_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_enabled', models.BooleanField(default=True, verbose_name='Sida (brud/brudgum)')),
                ('relation_enabled', models.BooleanField(default=True, verbose_name='Relation')),
                ('age_mode', models.CharField(choices=[('decades', 'Åldersgrupper (10-årsintervall)'), ('young_old', 'Ung/gammal')], default='decades', max_length=10)),
                ('age_split_cutoff', models.PositiveSmallIntegerField(default=30, help_text='Nedre gräns (år) för “Gammal” när Ung/gammal-läge används.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(119)])),
            ],
            options={
                'verbose_name': 'Event settings',
                'verbose_name_plural': 'Event settings',
            },
        ),
        migrations.AlterField(
            model_name='respondent',
            name='relation',
            field=models.CharField(blank=True, choices=[('friend', 'Vän'), ('family', 'Familj'), ('plus_one', 'Plus en')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='side',
            field=models.CharField(blank=True, choices=[('bride', 'Brudens sida'), ('groom', 'Brudgummens sida'), ('both', 'Bådas sida')], default='', max_length=8),
        ),
    ]
